title:              NewOrder Project
email:              katarina[dot]boland[at]hhu.de
description:        Understanding the erosion of the traditional knowledge order in scientific online discourse and its impact in times of crisis
author:             NewOrder Project
basewebsite:        /my-site
baseurl:            "/my-site"
url:                "https://startbootstrap.github.io"

# Social Profiles
github_username: NewOrder-Project
twitter_username: everydaymediaWG
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code
future: true  # allows posts with a date in the future, necessary for link to newOrder About in the news page

header_pages:
   - my-site/index.html
   - my-site/about.html
   - my-site/team.html
   - my-site/posts.html
   - my-site/news/index.html
   - my-site/contact.html


# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/news/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
