title:              Clean Blog
email:              your-email@example.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
basewebsite:        /my-site
baseurl:            "/my-site"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

header_pages:
   - index.html
   - about.html
   - team.html
   - 404.html
   - contact.html


# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
