title:              New Order Project
email:              katarina.boland@hhu.de
description:        Understanding the erosion of the traditional knowledge order in scientific online discourse and its impact in times of crisis
author:             Start Bootstrap
basewebsite:        /my-site
baseurl:            "/my-site"
url:                "https://startbootstrap.github.io"

# Social Profiles
github_username:    NewOrder-Project
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

header_pages:
   - my-site/index.html
   - my-site/about.html
   - my-site/team.html
   - my-site/posts/index.html
   - my-site/contact.html


# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
