# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NewOrder Project
email: katarina[dot]boland[at]hhu.de
description: >- # this means to ignore newlines until "baseurl:"
  Understanding the erosion of the traditional knowledge order in scientific online discourse and its impact in times of crisis
baseurl: "/my-site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: NewOrder-Project
twitter_username: everydaymediaWG
future: true  # allows posts with a date in the future, necessary for link to newOrder About in the news page
include:
  - my-site
# Build settings
theme: "jekyll-theme-clean-blog"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

markdown:           kramdown
paginate:           5
paginate_path:      "/news/page:num/"
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
   - /my-site/index.html
   - /my-site/workshops.html
   - /my-site/about.html
   - /my-site/team.html
   - /my-site/posts/index.html
   - /my-site/news/index.html
   - /my-site/contact.html


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
